"""Costanti dell'integrazione Netgear WAX214."""

DOMAIN = "wax214"
MANUFACTURER = "NETGEAR"

CONF_TRACK_CLIENTS = "track_clients"
DEFAULT_TRACK_CLIENTS = False
DEFAULT_PORT = 443
DEFAULT_USERNAME = "admin"
DEFAULT_SCAN_INTERVAL = 30
MIN_SCAN_INTERVAL = 10
